### ISSUE TITLE
UE 4.21

### ISSUE THREAD

**Issue by belko-vasiliy** [Pushwoosh/pushwoosh-unreal-engine#2]
Hello, I rebuilt pushwoosh sample project with plugin in it, and rebuild was succesfull.
But project can't deploy or build to android phone.

with no gradle:
ERROR: cmd.exe failed with args /c "C:/NVPACK/apache-ant-1.8.2/bin/ant.bat" debug -Djava.source=1.7 -Djava.target=1.7

with gradle there were problems:
PushOpenReceiver.java:5: error: package com.pushwoosh.internal does not exist
PushOpenReceiver.java:6: error: package com.pushwoosh.internal does not exist
and etc.

There was some warning problems with transition to 4.21, what i resolved, for example:
**.Build.cs : warning : Modules must specify an explicit precompiled header (eg. PrivatePCHHeaderFile = "Public/Pushwoosh.h") from UE 4.21 onwards.        and etc.

But one warning problem i didn't resolve :
LogPlayLevel: Warning:   D:\Unreal Projects\PushwooshSample\Plugins\Pushwoosh\Source\Pushwoosh\Pushwoosh.Build.cs: warning: Referenced directory 'C:\Program Files\Epic Games\UE_4.21\Engine\Source\Pushwoosh\Public' does not exist

so now i have errors: 
LogPlayLevel: Error:   D:/Unreal Projects/PushwooshSample/Plugins/Pushwoosh/Intermediate/Build/Android/UE4/Development/Pushwoosh/Module.Pushwoosh.cppa7.o:D:/Unreal Projects/PushwooshSample/Plugins/Pushwoosh/Intermediate/Build/Android/UE4/Development/Pushwoosh/Module.Pushwoosh.cpp:typeinfo for UPushwooshComponent: error: undefined reference to 'typeinfo for UActorComponent'
LogPlayLevel: Error:   D:/Unreal Projects/PushwooshSample/Plugins/Pushwoosh/Intermediate/Build/Android/UE4/Development/Pushwoosh/Module.Pushwoosh.cppa7.o:D:/Unreal Projects/PushwooshSample/Plugins/Pushwoosh/Intermediate/Build/Android/UE4/Development/Pushwoosh/Module.Pushwoosh.cpp:typeinfo for UPushwooshSettings: error: undefined reference to 'typeinfo for UObject'

Could you please rebuild your project with plugin for newer version of UE4 (4.21) ?

**Comment by wfhm** [comment]
@belko-vasiliy Fixed with the latest release.
