### ISSUE TITLE
Can't Deploy 

### ISSUE THREAD

**Issue by belko-vasiliy** [Pushwoosh/pushwoosh-unreal-engine#3]
@wfhm 
Hello! I finally rebuild plugin with no errors and warnings. But i have the same problem  without gradle:
Error: ERROR: cmd.exe failed with args /c "C:/NVPACK/apache-ant-1.8.2/bin/ant.bat" debug -Djava.source=1.7 -Djava.target=1.7
With Gradle also  same problems.
In what direction i should look to figure out with this problems?
If you want, I'll send you a project.

**Comment by wfhm** [comment]
@belko-vasiliy Fixed with the latest release.
